### ISSUE TITLE
Dev: Create organization profile

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-backend#104]
## Description
As a user associated to an organization,
I want to create an organization profile,
so that I can use it to create programs that the organization hosts.

## Acceptance Criteria
- [ ] Create organization profile - POST call

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

**Comment by mtreacy002** [comment]
@meenakshi-dhanani . Just like what we agreed on the Refactoring POST and PUT user that got refactored to only PUT so that create and update are both done using the PUT /user/... (for the purpose of keeping logic at backend, not frontend), the same will apply to Organization and Progrram. I think you can close this issue as I'm going to modify issue #105 PUT and GET organization profile to do get, create and update.
