### ISSUE TITLE
Bug: List programs for organization breaks because of 201 status code returned by mentorship API

### ISSUE THREAD

**Issue by meenakshi-dhanani** [anitab-org/bridge-in-tech-backend#120]
**Describe the bug**
For an organization, if programs need to be listed for a user that represents the organization, we do a GET call for /organizations/1/programs. This call needs to make an internal call GET/users/{user_id} to mentorship backend that ideally should return 200 but currently returns 201 status instead.

**To Reproduce**
 1. Login API to a user to login
 2. Update additional information and declare user as representative of organization
 3. Create an organization 
 4. Hit the GET api for querying programs in an organization that the user represents

  

**Expected behavior**
The call should return 404 for no programs found.

**Screenshots**
<img width="1388" alt="Screen Shot 2020-08-23 at 6 08 12 PM" src="https://user-images.githubusercontent.com/14279061/91472986-e3651a80-e8b5-11ea-8059-c26cfccd0558.png">

**Comment by mtreacy002** [comment]
@meenakshi-dhanani . I've done some digging. I suspect that this is probably because you haven't pulled the latest code of my ms-backend-server. I continuously updating this branch to keep up with the latest code being merged to the MS backend develop. So, this is not a static branch. The last commit from MS backend I pulled to this ms-backend-server is the PR that fixes that bug (Refactor GET /users/{user_id} from 201 to 201) which explains why I didn't get the same bug as you. 

commits on ms-backend-server atm:
<img width="1388" alt="Screen Shot 2020-08-28 at 9 16 58 am" src="https://user-images.githubusercontent.com/29667122/91505122-2fde4380-e912-11ea-9921-0037df00921f.png">

You need to pull my ms-backend-server again to make it work.

cc @anitab-org/bridgeintech-maintainers , 
In hindsight, ideally for every time we test a pr, before running the server we should check this:
**make sure the same commit IDs on the 3 servers we're going to run the test on match the commits ID on the servers that used on the PR** (ms-backend-server, bit backend pr, frontend pr)

This is to make sure we have the same environment when running the pr code. Otherwise any anomaly that comes up because of this unmatched servers could be mistakenly thought as a bug.

**Comment by meenakshi-dhanani** [comment]
Oh yes, I'm sorry I didn't pull the latest change. I pulled up the latest code on mentorship and it returns a 200. 
Though I feel that for the /programs API if a user is not found or hasn't declared he will represent and organization, an object with the user details should not be returned. Shouldn't it be an error code? Of course this can be a different topic @mtreacy002

**Comment by mtreacy002** [comment]
Let's try to see if after you pull the latest MS code for ms-backend-server, if this is still the case (/programs API if a user is not found or hasn't declared he will represent and organization returning an object with the user details), then we can open an issue for it.

**Comment by meenakshi-dhanani** [comment]
> Let's try to see if after you pull the latest MS code for ms-backend-server, if this is still the case (/programs API if a user is not found or hasn't declared he will represent and organization returning an object with the user details), then we can open an issue for it.

It's not about whether I get the issue or no, I don't think it's a right expectation. Like for any reason if a do not get programs from the API, an error code would be expected. A better way to handle a scenario as this would be to return an error is what I'm saying.

**Comment by mtreacy002** [comment]
@meenakshi-dhanani . If that's the concern then we don't have to do anything else, since the code already handled it properly as showing here:

* on BIT side: if the GET /users/{user_id} call to MS backend is not 200, then show user.message  

<img width="1030" alt="Screen Shot 2020-08-28 at 6 32 53 pm" src="https://user-images.githubusercontent.com/29667122/91539792-38a83700-e95d-11ea-8ffe-852cca7dc476.png">

which would be the error message returned by MS backend according to MS code below
<img width="849" alt="Screen Shot 2020-08-28 at 6 37 48 pm" src="https://user-images.githubusercontent.com/29667122/91540246-da2f8880-e95d-11ea-98f2-418acd01b747.png">

* in the case of user has not stated that they are a representative of an organization or if user additional info does not exist, shouldn't return an object of user, I think my fix on #121 actually also fix this bug. 

Here's my new user bsmith01 who has not created additional info

<img width="1680" alt="Screen Shot 2020-08-28 at 6 51 42 pm" src="https://user-images.githubusercontent.com/29667122/91541339-8c1b8480-e95f-11ea-8e89-41bd14dc5976.png">

when he tried to view Organisations/1/programs, he sees the programs list

<img width="1680" alt="Screen Shot 2020-08-28 at 6 48 06 pm" src="https://user-images.githubusercontent.com/29667122/91541445-bb31f600-e95f-11ea-863f-c90b0c495f09.png">

then when click view under Program to see that specific program, he sees the program details.
<img width="1680" alt="Screen Shot 2020-08-28 at 6 48 13 pm" src="https://user-images.githubusercontent.com/29667122/91541286-74440080-e95f-11ea-9c1f-8753cb3ab539.png">

you can test it yourself by running that PR #121 branch as Bit backend see if you have the same result.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . Closing this because this bug happened as the result of ncorrect ms-backend-server version was run along with BIT server.
