### ISSUE TITLE
Organization url dows not accept www.<string>.<string> format

### ISSUE THREAD

**Issue by rpattath** [anitab-org/bridge-in-tech-backend#145]
**Describe the bug**
Organization url dows not accept www.<string>.<string> format. Enter www.test.com and an error is shown

**To Reproduce**
1. Go to 'My Space -> My Organization'
2. Edit or create a new org
3. Enter www.any-string.com
4. 
![Screenshot from 2020-09-20 18-08-00](https://user-images.githubusercontent.com/26095715/93723492-e083df80-fb6c-11ea-9f38-b1358336139e.png)

**Expected behavior**
That url format sould be accepted

**Desktop (please complete the following information):**
 - OS:Fedora 32
 - Browser chrome

**Comment by mtreacy002** [comment]
@rpattath, this issue is related to frontend html <input> tag property "type" which we are using with value "url". 
<img width="1680" alt="Screen Shot 2020-09-21 at 9 42 45 am" src="https://user-images.githubusercontent.com/29667122/93724972-defafb80-fbee-11ea-967e-c11ea31780b4.png">

But this is not an issue originated from BIT. This is the default that the HTML use and we can't change (unless their changing their code internally). To be accepted as url, the string must have "http://" in front of the url string otherwise it will be rejected. You can try it yourself [here](https://www.w3schools.com/tags/att_input_type_url.asp)

When no "http://" provided
<img width="1680" alt="Screen Shot 2020-09-21 at 9 35 43 am" src="https://user-images.githubusercontent.com/29667122/93725018-3600d080-fbef-11ea-9b4f-2c637669bd6f.png">

When provided it shows that server has processed the input (don't worry about the warning message - it comes since there's no backend to accept the input)
<img width="1680" alt="Screen Shot 2020-09-21 at 9 36 04 am" src="https://user-images.githubusercontent.com/29667122/93725070-92fc8680-fbef-11ea-9ce7-0ed8405230e4.png">

So, can you please close the issue?
