### ISSUE TITLE
Bug: Unable to install all the python packages from requirements.txt

### ISSUE THREAD

**Issue by Aju100** [anitab-org/bridge-in-tech-backend#157]
**Describe the bug**
As mentioned in [docs](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup). I have followed every step and I was not able to install all the python packages so I can run in my local machine.

**To Reproduce**
1. clone the repo and make the virtual environment
2. pip install -r requirements.txt

>Note: you should activate the virtual environment

**Expected behavior**
Every package should be installed successfully.

**Screenshots**
![pip1](https://user-images.githubusercontent.com/29862610/94362176-36aad280-00d9-11eb-9ddd-e4ac794f9386.png)
![pip2](https://user-images.githubusercontent.com/29862610/94362195-52ae7400-00d9-11eb-853d-6482bc82fdf9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Python : 3.8.2

* Output Error *
Here is the ubuntu paste link of errors [log](https://paste.ubuntu.com/p/4XZvBypXZQ/).

**Comment by mtreacy002** [comment]
@Aju100 , Thank you for reporting this issue. This might be the same bug reported on Mentorship System backend issue [#578](https://github.com/anitab-org/mentorship-backend/issues/578). Removing the cffi package ([PR#713](https://github.com/anitab-org/mentorship-backend/pull/713)) from the dependencies actually worked for the Mentorship System. We might also need to do the same here on BridgeInTech. The only reason BIT is using cffi is because it was used in Mentorship System. Now that's no longer the case, we can remove it which also should help resolve your issue. Would you like to work on this issue?

**Comment by Aju100** [comment]
@mtreacy002  yeah sure. I would love to work on this issue. As I am a beginner in opensource and would love to contribute and engage in the community.

**Comment by devkapilbansal** [comment]
@mtreacy002 wouldn't it be better if the requirements file is audited. Similar to anitab-org/mentorship-backend#881 As the same bug was there to like:- anitab-org/mentorship-backend#713

**Comment by mtreacy002** [comment]
@devkapilbansal . This sounds like a good idea. Can you please open an issue for it (auditing the dependencies)?
