### ISSUE TITLE
Use HTTPStatus code values instead of enum representation, in Users API

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/bridge-in-tech-backend#178]
**Describe the bug**

The values shown on Swagger UI of Users API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK. 

**To Reproduce**

1. Go to https://bridgeintech-bit-heroku-psql.herokuapp.com/
2. Scroll down to ```Users Api```
3. See enum representation.

![image](https://user-images.githubusercontent.com/66299533/104735665-df07a400-5767-11eb-9051-a86070b916b4.png)

**Expected behavior**
Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**
 - OS: Ubuntu 20+
 - Browser FireFox Web Browser
 - Version --

**Comment by Aaishpra** [comment]
@mtreacy002 I was working on an issue on the mentorship backend [here](https://github.com/anitab-org/mentorship-backend/issues/939#issue-773523175) and thought BIT needs a similar issue so I opened one. Actually, the values shown on BIT's swagger UI should be in real number format instead of enum representation, in the code, it should use the enum representation but in the swagger, the values displayed should be in real number format. The suitable approach which also worked for mentorship-backend was using HTTPStatus.x.value in place of HTTPStatus.x.

If you feel this issue is valid, I would like to work on this here too.

**Comment by devkapilbansal** [comment]
@Aaishpra this issue seems valid to me, however @mtreacy002 can confirm this.
Also, I would suggest to look into other issues and leave it for newcomers only as it is not urgent

**Comment by Aaishpra** [comment]
Sure thing 👍 @mtreacy002 you can label this as a first timer.

**Comment by mtreacy002** [comment]
@devkapilbansal and @Aaishpra , I understand why you raised this issue. However, as per suggested by my mentor @ramitsawhney27 During GSoC, it is best to give the information on swagger as the actual enum representation of the httpStatus since this way the information given as feedback to the developer is more meaningful (e.g. httpStatus.Conflict vs 409). If the number is given, developer might not immediately know that 409 stands for Conflict and might need to lookup for what it represents before investigating the issue. Perhaps we can open an issue on Mentorship System backend side for the enum representation to be applied on swagger instead? Cc @isabelcosta

**Comment by nlok5923** [comment]
@mtreacy002 please can you assign me this issue.

**Comment by mtreacy002** [comment]
@nlok5923 , I hope to hear to @ramitsawhney27 and @isabelcosta opinion on this matter first before approving the issue and assign it to anyone. Hope this make sense 😉.

**Comment by Aaishpra** [comment]
@mtreacy002 the issue itself was suggested by @isabelcosta [here](https://github.com/anitab-org/mentorship-backend/issues/846#issuecomment-749527038)

Cc @isabelcosta

**Comment by isabelcosta** [comment]
@mtreacy002 are you sure that the suggestion was about what shows up on Swagger UI or in the code?
I suggested showing on swagger because when we use representation of enum, and you make an API request, you will see a message from swagger saying that the HTTP code was undocumented.

Here's an official example of Swagger UI should look like: https://petstore.swagger.io/#/pet/updatePetWithForm
If you click an API, you'll have codes as numbers.

Here's an example when using Bridge in Tech API:

![swagger UI showing that 401 HTTP status code is undocumented](https://user-images.githubusercontent.com/11148726/105644376-2c34f580-5e8d-11eb-80e7-650e0e3d348d.png)

In the image, can be seen that 401 appears to be undocumented when in reality it is documented, but using HTTPStatus representation instead of the actual code.

I still stand by using the enum, in code, to be more clear to the developer, when reading the code, what is being used. However on Swagger, showing the enum, it's revealing implementation details (i.e., we are using HTTPStatus enum).

Let me know what you think, considering this.
(sorry for the delay in my input 🙇‍♀️)

cc @devkapilbansal @Aaishpra @mtreacy002

**Comment by mtreacy002** [comment]
That makes sense, @isabelcosta (we don't want the response to be shown as "undocumented "). Thank you for your explanation. I'm happy to approve this issue now 😉.

**Comment by mtreacy002** [comment]
@nlok5923 , are you still interested working on the issue? If you do, I'll assign you to it 😉.

**Comment by Aaishpra** [comment]
> @nlok5923 , are you still interested working on the issue? If you do, I'll assign you to it 😉.

@mtreacy002 in my view he has already contributed to the project, so he isn't eligible to work on a first-timer issue I guess.🤔
In my opinion this issue can be a great start for someone who's completely new to the project as @devkapilbansal also suggested cause this issue is not very urgent..

Also, shall I open similar issue for organisations API.

Hope to hear your opinion 😆

**Comment by mtreacy002** [comment]
@Aaishpra , in fact, I noticed you haven't submitted PR to the backend repo (do correct me if I'm wrong 😁). Would you like to work on this issue since you opened it? This could be your first-time contribution to the backend 😉.

And yes, please, you can open the same for other API as well. Thank you again for bringing this up 👍.

**Comment by Aaishpra** [comment]
> @Aaishpra , in fact, I noticed you haven't submitted PR to the backend repo. Would you like to work on this issue since you opened it? This could be your first-time contribution to the backend 😉.
> 
> And yes, please, you can open the same for other API as well. Thank you again for bringing this up 👍.

Why not if I am eligible for it😆. Will open one soon thanks.

**Comment by Aaishpra** [comment]
@mtreacy002 I just checked I have already submitted two PR's here (for the backend repo), so I am also not eligible to be working here :(
but I can surely help to guide and review the PR I guess.
This issue should be made available for someone contributing first time here or to the project, sorry for the confusion though.

**Comment by mtreacy002** [comment]
Agree, @Aaishpra . Thanks for letting me know about your previous contributions. Let's wait for a new contributor to claim the issue then 😉.

**Comment by chinmaym07** [comment]
Hey @mtreacy002 Can I take this up .?

**Comment by mtreacy002** [comment]
@chinmaym07 , haven't you contributed to the BIT backend repo before? If you haven't, I'll assign you to this issue. Otherwise, we should leave it to someone who hasn't contributed yet.

**Comment by chinmaym07** [comment]
> @chinmaym07 , haven't you contributed to the BIT backend repo before? If you haven't, I'll assign you to this issue. Otherwise, we should leave it to someone who hasn't contributed yet.

I think I have contributed to BIT ..Yes sure ..It's definitely a good first issue for new contributors to get started.. 👍🏻 😀

**Comment by ganatra-v** [comment]
Hello @mtreacy002 , I am new here, and would love to start contributing to this project with this issue. Could you please assign it to me?

**Comment by mtreacy002** [comment]
Sure, @Vaibhav-Ganatra . Welcome and thanks for picking up the issue. I'll assign you to this.
