### ISSUE TITLE
Migrate to github actions

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/bridge-in-tech-backend#192]
**Is your feature request related to a problem? Please describe.**
Add github actions to test pull requests so we can get a precise report of the pull request whether the tests are passing or not etc.

**Comment by vj-codes** [comment]
@mtreacy002 hey can you review/approve this issue?
I know the description is really short but wasn't sure what else to add, can be edited later.
Also I would like to work on this please.

**Comment by mtreacy002** [comment]
Yep, @vj-codes , it's a valid issue. And I think the PR once submitted will need to be approved and merge first before the Black formatter issue, then we can see the build that is missing in #191 . I'll assign you to this now.

**Comment by vj-codes** [comment]
@mtreacy002 acc to my observations the  travis ci build is missing in 5 out of the 7 open pull requests open , it used to be there earlier any idea why travis is missing 🤔

**Comment by mtreacy002** [comment]
😱 I'll go and check. Thanks for bringing it up @vj-codes , I didn't realise this.

**Comment by mtreacy002** [comment]
@vj-codes . I believe this is due to Travis migration from travis-ci.org to travis-ci.com. But we're still using the travis-ci.org on our Readme so we need to change it.

on travis-ci.org:
<img width="1299" alt="Screen Shot 2021-02-17 at 8 25 06 am" src="https://user-images.githubusercontent.com/29667122/108124004-cbe74b80-70fa-11eb-8925-151f18f818c1.png">

on travis-ci.com
<img width="1120" alt="Screen Shot 2021-02-17 at 8 25 22 am" src="https://user-images.githubusercontent.com/29667122/108123967-beca5c80-70fa-11eb-8bf7-fb6f9ddaf2a0.png">

on Readme file
<img width="742" alt="Screen Shot 2021-02-17 at 8 24 58 am" src="https://user-images.githubusercontent.com/29667122/108124065-dd305800-70fa-11eb-80c3-29010e15bc47.png">

@isabelcosta , is there something I can do from my end to refer Travis to link to the new travis-ci.com or is it a task only an admin can do?

**Comment by vj-codes** [comment]
@mtreacy002 give these a try , I gave it a quick look and
Apparently there's some sorta beta test that needs to be joined and only ones with higher authority can do it.
https://docs.travis-ci.com/user/migrate/open-source-repository-migration
https://discourse.mc-stan.org/t/travis-ci-org-problems-migration-to-travis-ci-com/14148

**Comment by mtreacy002** [comment]
@isabelcosta , I've tried to look for the variables needed to make the changes as suggested on the first link referred to by @vj-codes above, but I can't see these options on my end (perhaps because I have no admin access to the AnitaB Travis repo?) 
<img width="759" alt="Screen Shot 2021-02-17 at 9 45 37 am" src="https://user-images.githubusercontent.com/29667122/108131396-50d76280-7105-11eb-859f-b3b47be0297a.png">

Can you please help?

**Comment by vj-codes** [comment]
@mtreacy002 yes we do use protected branches in BIT .
Shall I wait until the travis is back and then create a PR ?
cc: @isabelcosta

**Comment by isabelcosta** [comment]
What exactly do you need from admins @vj-codes @mtreacy002 
The idea is to still move to GitHub actions and deprecate TravisCI usage :)

**Comment by vj-codes** [comment]
@isabelcosta when we do create GitHub action and the build is successful on my fork we'll still need to check if the current travis build is passing and it's not breaking anything so for that it will be needed . 
But at the moment travis is missing in the repo as it's migrated from travisci.org to travisci.com so we needed admins to update travis just to crosscheck the gh actions PR is successful l.

**Comment by mtreacy002** [comment]
@vj-codes , I think once you submit the code change for this PR, the .github/workflows/main.yml will trigger build with GitHub actions and we can see if the tests pass or not. The travis.yml will be removed in the code changes anyway, so we don't have to worry about Travis CI, right? The black issue #191 can be revisited once the PR of this issue Is approved 😉.

**Comment by vj-codes** [comment]
@mtreacy002 since the deploy to gh pages issues is opened again , is this issue valid?

**Comment by mtreacy002** [comment]
Yes, @vj-codes , this issue is valid. But to be clear, this issue is separate from the gh-pages on frontend.
The backend gh-pages remains as an invalid issue. But regardless of gh-pages, the CI need to be moved from Travis CI to GitHub action, which is the task on this PR. Will you be able to continue to work on this?

**Comment by vj-codes** [comment]
@mtreacy002 yes I would like to continue, will create a PR  in few hours , I have done the changes locally need to push them and check if all actions are succesfull ir not:)

**Comment by mtreacy002** [comment]
@vj-codes . You can use this Mentorship backend [issue 1029](https://github.com/anitab-org/mentorship-backend/pull/1029) as reference for running the tests. That MS backend issue has successfully passed all tests. Thanks to @epicadk who has helped me with the process 😉.

**Comment by vj-codes** [comment]
@mtreacy002 thanks for sharing it is definitely helping with the error I got :)

**Comment by vj-codes** [comment]
@mtreacy002 I'm done , I just had a small ques , my fork is currently 4 commits behind develop , is it mandatory to sync it the branch I created for gh actions?

**Comment by epicadk** [comment]
> @mtreacy002 I'm done , I just had a small ques , my fork is currently 4 commits behind develop , is it mandatory to sync it the branch I created for gh actions?

I guess it would be better if you merge the changes so we can check if all the tests pass.

**Comment by vj-codes** [comment]
ah okay thanks @epicadk

**Comment by vj-codes** [comment]
@mtreacy002 I pushed the changes but the tests were failing earlier due to PostgreSQL error from my side, but then I updated the workflow almost the same as the one you've linked above but they are still failing. Any idea how to fix it?

**Comment by epicadk** [comment]
> @mtreacy002 I pushed the changes but the tests were failing earlier due to PostgreSQL error from my side, but then I updated the workflow almost the same as the one you've linked above but they are still failing. Any idea how to fix it?

Can you open a pr so we can help you out?

**Comment by epicadk** [comment]
> @mtreacy002 I pushed the changes but the tests were failing earlier due to PostgreSQL error from my side, but then I updated the workflow almost the same as the one you've linked above but they are still failing. Any idea how to fix it?

Also @mtreacy002 this is another reason to use docker because the development, test and production environments are almost the same 😉

**Comment by mtreacy002** [comment]
@epicadk I agree, docker has its advantages. But still personally, I like the non-container option, so let's can keep them both for now. We'll see how these 2 (docker and venv) being used by our contributors then decide if we only need to keep one.

**Comment by decon-harsh** [comment]
I agree @mtreacy002 most of the new contributors have less or no idea about docker. I personally found it really tough. BIT should have both the options.
