### ISSUE TITLE
Feat: Add GET endpoint /users/{userId}/additional-info to fetch additional information from userId

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-backend#215]
### Is your feature request related to a problem? Please describe.
Although we have endpoint /additional-info for a to fetch additional details of current user (using access_token). We don't have endpoint for a user (org representative) requesting additional-information of other user.

### Describe the solution you'd like
There should be a GET endpoint `/users/{userId}/additional-info` for fetching a user's additional information from userId.

### Additional context
Refer to the discussion [here](https://github.com/anitab-org/bridge-in-tech-web/issues/155).

**Comment by mtreacy002** [comment]
@Rahulm2310 , thank you for raising this issue. Would you like to work on it?

**Comment by Rahulm2310** [comment]
@mtreacy002 I think this can be a good opportunity for OSH aspirants. Let them claim this 😊

**Comment by naveen8801** [comment]
hi @mtreacy002 @Rahulm2310  , actually this is the first time i am dealing with backend , please help me in getting started  :-)

**Comment by mtreacy002** [comment]
Sure, should I assign you to this, @naveen8801 ?

**Comment by naveen8801** [comment]
> Sure, should I assign you to this, @naveen8801 ?

Yaa , i'd like to work it ,

**Comment by naveen8801** [comment]
Hi @mtreacy002 , i have created a route ' users/<int:user_id>/additional_info ' in users.py under resources folder and its working fine by giving back the response containing additional data of user with user_id ( if additional info is saved) , otherwise " No additional information found with this user id. Please provide them now" 

![Screenshot (59)](https://user-images.githubusercontent.com/54985099/116772390-58ec4080-aa6c-11eb-9aa3-ad12a77e55c1.png)

Is there any documentation to be made or should i create a PR ?

**Comment by mtreacy002** [comment]
@naveen8801 , that's great. You can submit the pr now and we can give you feedback on it directly on what else need to be added (if any) 😉 .
