### ISSUE TITLE
Deploy Mentorship Backend on Heroku with ElephantSQL instance

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/bridge-in-tech-backend#22]
## Description

It would really help @mtreacy002 having a separate instance of Heroku server with mentorship backend so we have a sandbox environment, not interfering with mentorship backend already existing data.

### Update [Required]
- [x] Deploy to Heroku Mentorship Backend
- [x] Create an ElephantSQL instance for Maya, or have her creating and giving me the credentials 🤷‍♀️ 
- [x] Provide credentials to Maya

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
who know how many hours

**Comment by isabelcosta** [comment]
Heroku server for Mentorship Backend is created and deployed here: https://mentorship-backend-bit.herokuapp.com/

@mtreacy002 has the credentials to the ElephantSQL instance and we share the app on Heroku.
Admin user is already created and we tested this in our 1:1 today.
The server code comes from my fork of mentorship-backend, in particular from `heroku` branch.

**Comment by mtreacy002** [comment]
Thanks so much for your help, @isabelcosta ❤️ . I'll also look into your suggestion and see if I can create one from my fork...😉

**Comment by mtreacy002** [comment]
Update: 
@anitab-org/bridgeintech-maintainers. I've managed to deploy my own [heroku server](https://bridge-in-tech-ms-test.herokuapp.com/swagger.json) from my forked repo **[heroku-ms-backend](https://github.com/mtreacy002/mentorship-backend/tree/heroku-ms-backend)** branch with the same ElephantSQL instance db set with @isabelcosta last night. 🎉 
<img width="832" alt="Screen Shot 2020-05-31 at 11 58 59 am" src="https://user-images.githubusercontent.com/29667122/83342843-543c7b00-a337-11ea-95ed-20678a2e8ad2.png">

And the best thing is, I can now see the debug console working when I interact with this Heroku swagger UI 💃 💃 💃 

<img width="1680" alt="Screen Shot 2020-05-31 at 12 09 44 pm" src="https://user-images.githubusercontent.com/29667122/83342946-1ee45d00-a338-11ea-8cd9-2ff31a338715.png">


I'll be using this as my test MS API for the initial stage of GSoC.
I'll slowly explore the possibilities to add BIT schema into the ms code base on this branch so that BIT and MS can hopefully have one db in the future.
