### ISSUE TITLE
Fix tests failing on github actions

### ISSUE THREAD

**Issue by epicadk** [anitab-org/bridge-in-tech-backend#262]
### Describe the bug

Tests on github actions are failing.

### To Reproduce
1. Check the actions tab 

### Expected behavior

Tests should not fail

**Comment by y-martinez** [comment]
> ### Describe the bug
> Tests on github actions are failing.
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Check the actions tab
> 
> ### Expected behavior
> Tests should not fail
> 
> ### Additional context

It is a problem weird because it does not always happen, I have the theory (I could be wrong) that it happens when the postgres container has not started because the error is in there, so, I searched the internet and it is that the postgres container does not provide a health check, so you need to add options to the github actions configuration, specifically something like this:


```
# Set health checks to wait until postgres has started
options: >-
  --health-cmd pg_isready
  --health-interval 10s
  --health-timeout 5s
  --health-retries 5
```

I haven't tried it so I'm not sure if it's a possible solution

**Comment by epicadk** [comment]
Yeah that was the solution. Would you like to work on this? 
Great job figuring it out.

**Comment by y-martinez** [comment]
Yeah sure!

**Comment by epicadk** [comment]
Okay, good luck. Assigning you. 👍

**Comment by vj-codes** [comment]
@epicadk are you talking about the docusaurus PR failing?

**Comment by epicadk** [comment]
> @epicadk are you talking about the docusaurus PR failing?

Yeah but in any case these options should be added.
